slackpkg-2.70beta2-noarch-1

diff --git a/usr/sbin/slackpkg b/usr/sbin/slackpkg
--- a/usr/sbin/slackpkg
+++ b/usr/sbin/slackpkg
@@ -32,17 +32,17 @@
 # CONF = configuration directory
 # SOURCE = A mirror of Slackware. Source can be sett by editing $CONF/mirrors
 #
-VERSION=2.70beta
+VERSION=2.70beta2
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
-SLACKWARE_VERSION=`cat /etc/slackware-version | cut -f2 -d\ `
+SLACKWARE_VERSION=$(cat /etc/slackware-version | cut -f2 -d\ )
 SLACKKEY="Slackware Linux Project <security@slackware.com>"
 CONF=/etc/slackpkg
-SOURCE=`grep -e "^\([a-z]\)" $CONF/mirrors`
+SOURCE=$(grep -e "^\([a-z]\)" $CONF/mirrors)
 . $CONF/slackpkg.conf
 ARCH=${ARCH:-i[3456]86}
 LOCAL=0
-KERNELMD5=`md5sum /boot/vmlinuz 2>/dev/null`
-TMPDIR=`mktemp -p /tmp -d slackpkg.XXXXXX 2>/dev/null || echo "FAILED"`
+KERNELMD5=$(md5sum /boot/vmlinuz 2>/dev/null)
+TMPDIR=$(mktemp -p /tmp -d slackpkg.XXXXXX 2>/dev/null || echo "FAILED")
 if [ "$TMPDIR" = "FAILED" ]; then
 	TMPDIR="/tmp/slackpkg.${RANDOM}"
 	mkdir -m 700 $TMPDIR || TMPDIR="FAILED"
@@ -137,7 +137,7 @@ while [ -n "$1" ] ; do
       shift
     ;;
     -mirror=*)
-	SOURCE=`echo $1 | cut -f2 -d=`
+	SOURCE=$(echo $1 | cut -f2 -d=)
 	shift
     ;; 
     install|reinstall|upgrade|remove|search|blacklist|info)
@@ -146,7 +146,7 @@ while [ -n "$1" ] ; do
       if [ -n "$1" ]; then
         if echo $1 | egrep -q "^\.{0,2}/" ; then
 		if [ -e $1 ]; then
-			INPUTLIST=`cat $1 | tr "\n" " "`
+			INPUTLIST=$(cat $1 | tr "\n" " ")
 		else
 			echo -e "The file $1 doesn't exist.\n"
 			cleanup
@@ -156,7 +156,7 @@ while [ -n "$1" ] ; do
 		# Sanitize the argument. We have some problems with dots 
 		# and plus (.+)
 		#
-		#INPUTLIST="`echo $@ | sed -e 's/\+/\\\+/g' -e 's/\./\\\./g'`"
+		#INPUTLIST="$(echo $@ | sed -e 's/\+/\\\+/g' -e 's/\./\\\./g')"
 		INPUTLIST="$@"
         fi
       elif [ "$CMD" != "blacklist" ]; then
@@ -236,7 +236,7 @@ case "$CMD" in
 			gpg --yes --batch --delete-key "$SLACKKEY" &>/dev/null
 			gpg --import $TMPDIR/gpgkey &>/dev/null && \
 			echo -e "\t\t\tSlackware Linux Project's GPG key added"
-			if [ "$PATTERN" ]; then
+			if [ "$UPARG" = "gpg" ]; then
 				cleanup
 			fi
 		fi
@@ -328,7 +328,7 @@ case "$CMD" in
 			fi
 			for i in glibc-solibs readline pkgtools sed; do
 				FOUND=""
-				FOUND=`echo $SHOWLIST | tr -s ' ' "\n" | grep "${i}-[0-9]"`
+				FOUND=$(echo $SHOWLIST | tr -s ' ' "\n" | grep "${i}-[0-9]")
 				if [ "$FOUND" != "" ]; then 
 					getpkg $FOUND upgradepkg Upgrading
 				fi
@@ -351,7 +351,7 @@ case "$CMD" in
 		#
 		# If blacklist is called without package name, list
 		# all blacklisted packages
-		if [ "$PATTERN" = "" ]; then
+		if [ "$INPUTLIST" = "" ]; then
 			echo -e "Packages in blacklist:\n"
 			grep -e "^\([a-z]\)" $CONF/blacklist | more
 			cleanup
@@ -359,10 +359,10 @@ case "$CMD" in
 		
 		makelist ${INPUTLIST}
 		for i in $LIST; do
-			BASENAME=`cutpkg $i`
+			BASENAME=$(cutpkg $i)
 			BLACKLIST="$BLACKLIST $BASENAME"
 		done
-		BLACKLIST=`echo $BLACKLIST | tr ' ' "\n"`
+		BLACKLIST=$(echo $BLACKLIST | tr ' ' "\n")
 		if [ "$BLACKLIST" = "" ]; then
 			echo -e "No packages match the pattern."
 			cleanup
@@ -376,8 +376,8 @@ case "$CMD" in
 		# Search filelist.gz for possible matches
 		for i in $FIRST $SECOND $THIRD $FOURTH $FIFTH ; do
 			if [ -e ${WORKDIR}/${i}-filelist.gz ]; then
-				PKGS="`zegrep $PATTERN ${WORKDIR}/${i}-filelist.gz | \
-					cut -d\  -f 1 | awk -F'/' '{print $NF}'`"
+				PKGS="$(zegrep $INPUTLIST ${WORKDIR}/${i}-filelist.gz | \
+					cut -d\  -f 1 | awk -F'/' '{print $NF}')"
 				for j in $PKGS ; do
 					NEWONE=`cutpkg ${j}`
 					echo $PACKAGES | \
@@ -430,7 +430,7 @@ The list below shows all packages with the selected pattern.\n"
 		fi
 	;;
 	"info")
-		NAME=`cutpkg $PATTERN`
+		NAME=$(cutpkg $PATTERN)
 		awk -F: "/PACKAGE NAME:.* ${NAME}-[^-]+-(${ARCH}|noarch)-[[:digit:]]+/,/^$/ {
                                 found=1
 				 if (\$1 ~ /"$NAME"/) {
